### PR TITLE
[SQL-DS-CACHE-181][SDLe]Fix Snyk code scan issues

### PR DESCRIPTION
**Pull request by HongW2019**
## What changes were proposed in this pull request?

Bump Hadoop version of HCFS-SQL-DS-Cache to 3.3.1
Bump jackson-module-scala-2.12 version to 2.12.4

## How was this patch tested?

Pass the Snyk scan.

### CODE REVIEW

**Comment by HongW2019** [comment]
@zhixingheyi-tian Please take a review, thanks!

**Comment by zhixingheyi-tian** [comment]
@HongW2019 please check with @yeyuqiang @yma11 about the version upgrade

**Comment by HongW2019** [comment]
> @HongW2019 please check with @yeyuqiang @yma11 about the version upgrade

 @yeyuqiang @yma11 Please take a review, thanks a lot!

**Comment by yma11** [comment]
okay for me. But it will be tested, right?

**Comment by HongW2019** [comment]
> okay for me. But it will be tested, right?

It passed Snyk scan and current UTs.

**Comment by HongW2019** [comment]
> okay for me. But it will be tested, right?

@yma11  It passed Snyk scan and current UTs.

**Pull request merged**
