### PR TITLE
[SQL-DS-CACHE-29][POAE7-920]add github action CI for ape module

### PR DESCRIPTION
**Pull request by jikunshang**
## What changes were proposed in this pull request?

add github action CI for ape-java module

## How was this patch tested?

CI

### CODE REVIEW

**Comment by jikunshang** [comment]
@iyupeng @winningsix @xieqi Please take a review.
pom.xml files copy from PR#26, will do rebase later.

**Comment by iyupeng** [comment]
LGTM.

**Comment by winningsix** [comment]
+1

**Comment by jikunshang** [comment]
Both CPP and Java build passed. Merged :)

**Comment by jikunshang** [comment]
Sorry I forget to click squash and commit, I will reset to a previous parent and re-push to keep commit log clean.

**Pull request merged**
