### PR TITLE
[SQL-DS-CACHE-67][POAE7-967] Agg native support for int/long type

### PR DESCRIPTION
**Pull request by xieqi**
## What changes were proposed in this pull request?

Add agg native support for int/long type

## How was this patch tested?

manual tests

### CODE REVIEW

**Review by jikunshang — APPROVED** [review]
LGTM. cc @iyupeng

**Comment by iyupeng** [comment]
Hi @xieqi @jikunshang , 
I'm not very clear that why we need to convert all data types into `decimal` in APE?  Can we compute agg on the original data?
In my understanding, the result data need to be converted back to the requested data types.

**Comment by jikunshang** [comment]
> Hi @xieqi @jikunshang ,
> I'm not very clear that why we need to convert all data types into `decimal` in APE? Can we compute agg on the original data?
> In my understanding, the result data need to be converted back to the requested data types.

Yes, you're right, for `float` and `double` type, it will convert to `decimal` type, do comupte and convert back which may have some perfomance overhead. But I think this is more friendly to aggregation compute model.  

Otherwise, we need to maintain more template comute class(lile 'Sum', 'Add' and others) to handle type issue. For example, we may have `Sum<Decimal>`, `Sum<Float>`, `Sum<double>`, and we need some common APIs and `getResult ` method will be much more complex.  Of course we can have a try to implement the way you suggest.

**Comment by iyupeng** [comment]
> > Hi @xieqi @jikunshang ,
> > I'm not very clear that why we need to convert all data types into `decimal` in APE? Can we compute agg on the original data?
> > In my understanding, the result data need to be converted back to the requested data types.
> 
> Yes, you're right, for `float` and `double` type, it will convert to `decimal` type, do comupte and convert back which may have some perfomance overhead. But I think this is more friendly to aggregation compute model.
> 
> Otherwise, we need to maintain more template comute class(lile 'Sum', 'Add' and others) to handle type issue. For example, we may have `Sum<Decimal>`, `Sum<Float>`, `Sum<double>`, and we need some common APIs and `getResult ` method will be much more complex. Of course we can have a try to implement the way you suggest.

OK. Thanks for the reply.  Approved this pr.

**Review by iyupeng — APPROVED** [review]

**Pull request merged**
