### PR TITLE
[SQL-DS-CACHE-43][POAE7-960]enable code style check for ape

### PR DESCRIPTION
**Pull request by jikunshang**
## What changes were proposed in this pull request?

enable code style check for ape

## How was this patch tested?

CI test

### CODE REVIEW

**Comment by jikunshang** [comment]
Just modify code style, didn't touch any logic.
@winningsix @iyupeng @xieqi Please take a review, thanks!

**Comment by winningsix** [comment]
This close #43.

**Comment by jikunshang** [comment]
@winningsix forget to squash. I will do it manually.

**Comment by jikunshang** [comment]
see commit b6738c39d9e7366b34e883c680599bf19f7f1f79

**Comment by winningsix** [comment]
@jikunshang how do you fix this?

**Comment by jikunshang** [comment]
> @jikunshang how do you fix this?

remove merge commit, squash other commits, forch push.
And we should enable squash commit only when merge a pr, I remember it's in repo settings.

**Comment by winningsix** [comment]
@jikunshang I updated it.

**Pull request merged**
