### PR TITLE
[SQL-DS-CACHE-14][POAE7-847] Port HCFS to OAP

### PR DESCRIPTION
**Pull request by xieqi**
## What changes were proposed in this pull request?

Add HCFS module

## How was this patch tested?

UT

### CODE REVIEW

**Comment by winningsix** [comment]
A OAP issue needs to be created to make PR checker happy.

**Comment by winningsix** [comment]
Thanks @xieqi for quick updates. A few comments:
1. Let's have a separated module here. We should try best to isolate Spark dependency for HCFS module.
2. A few follow-up PRs are needed like documentation,

**Comment by winningsix** [comment]
@xieqi let's make this two steps: 1. refactor original code to make it a sub-module; 2. merge HCFS implementation into this repo.

**Comment by xieqi** [comment]
@winningsix rebased and include the Yu's latest optimization.

**Pull request merged**
